# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(628, 476)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_YoutubeLink = QtWidgets.QLineEdit(self.centralwidget)
        self.input_YoutubeLink.setEnabled(True)
        self.input_YoutubeLink.setGeometry(QtCore.QRect(130, 10, 431, 41))
        self.input_YoutubeLink.setObjectName("input_YoutubeLink")
        self.textYoutube_Link = QtWidgets.QTextBrowser(self.centralwidget)
        self.textYoutube_Link.setGeometry(QtCore.QRect(20, 10, 101, 41))
        self.textYoutube_Link.setObjectName("textYoutube_Link")
        self.button_fetch = QtWidgets.QPushButton(self.centralwidget)
        self.button_fetch.setGeometry(QtCore.QRect(460, 60, 93, 28))
        self.button_fetch.setObjectName("button_fetch")
        self.preview_ss = QtWidgets.QLabel(self.centralwidget)
        self.preview_ss.setEnabled(True)
        self.preview_ss.setGeometry(QtCore.QRect(270, 310, 331, 101))
        self.preview_ss.setText("")
        self.preview_ss.setPixmap(QtGui.QPixmap("WhatsApp Image 2022-12-24 at 14.17.40.jpeg"))
        self.preview_ss.setObjectName("preview_ss")
        self.textPreiew_ss = QtWidgets.QTextBrowser(self.centralwidget)
        self.textPreiew_ss.setGeometry(QtCore.QRect(150, 330, 121, 61))
        self.textPreiew_ss.setObjectName("textPreiew_ss")
        self.textNormal = QtWidgets.QTextBrowser(self.centralwidget)
        self.textNormal.setGeometry(QtCore.QRect(160, 200, 171, 91))
        self.textNormal.setObjectName("textNormal")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(330, 200, 171, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 190, 131, 191))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 111, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comment = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.comment.setEnabled(False)
        self.comment.setChecked(True)
        self.comment.setObjectName("comment")
        self.verticalLayout.addWidget(self.comment)
        self.userName = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.userName.setChecked(True)
        self.userName.setObjectName("userName")
        self.verticalLayout.addWidget(self.userName)
        self.likes = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.likes.setObjectName("likes")
        self.verticalLayout.addWidget(self.likes)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.screenShot = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.screenShot.setObjectName("screenShot")
        self.verticalLayout.addWidget(self.screenShot)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 60, 261, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 241, 74))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.count_minLikes = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.count_minLikes.setEnabled(False)
        self.count_minLikes.setMaximum(99999)
        self.count_minLikes.setObjectName("count_minLikes")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.count_minLikes)
        self.checkBox_maxComment = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_maxComment.setChecked(True)
        self.checkBox_maxComment.setObjectName("checkBox_maxComment")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_maxComment)
        self.count_maxComments = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.count_maxComments.setEnabled(True)
        self.count_maxComments.setMaximum(99999)
        self.count_maxComments.setProperty("value", 30)
        self.count_maxComments.setObjectName("count_maxComments")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.count_maxComments)
        self.checkbox_minLike = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkbox_minLike.setObjectName("checkbox_minLike")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkbox_minLike)
        self.checkBox_mustFindText = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_mustFindText.setObjectName("checkBox_mustFindText")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_mustFindText)
        self.inputText_mustFindText = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.inputText_mustFindText.setEnabled(False)
        self.inputText_mustFindText.setObjectName("inputText_mustFindText")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inputText_mustFindText)
        self.warning = QtWidgets.QLabel(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(210, 70, 201, 16))
        self.warning.setText("")
        self.warning.setObjectName("warning")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 628, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textYoutube_Link.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Youtube Video Link :</span></p></body></html>"))
        self.button_fetch.setText(_translate("MainWindow", "Fetch"))
        self.textPreiew_ss.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Preiew of Screnshots that will be taken:</span></p></body></html>"))
        self.textNormal.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Comment will save in \'comments.txt\'<br /><br />With this format :</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">--------------------<br />User name<br />Comment</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Likes<br />--------------------</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Save options"))
        self.comment.setText(_translate("MainWindow", "Save Comment"))
        self.userName.setText(_translate("MainWindow", "Save User Name"))
        self.likes.setText(_translate("MainWindow", "Save Like Count"))
        self.screenShot.setText(_translate("MainWindow", "Take as SS"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Conditions"))
        self.checkBox_maxComment.setText(_translate("MainWindow", "Max comment count"))
        self.checkbox_minLike.setText(_translate("MainWindow", "Minumum Like "))
        self.checkBox_mustFindText.setText(_translate("MainWindow", "Must inculude this text"))
